// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhpwzhqvchilvdvznmqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocHd6aHF2Y2hpbHZkdnpubXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDQ0NjIsImV4cCI6MjA2MzEyMDQ2Mn0.ROqIwcSbtbauh7-Q6hJa1owueApUZHm58aaNluwbOzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);