// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strutcqjegnwidtfonhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cnV0Y3FqZWdud2lkdGZvbmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDI0OTksImV4cCI6MjA2MzExODQ5OX0.QgpUsfXRy3QDJS4hCzkImUfg1QhLLaBUs4sqDqifVeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);